### PR TITLE
fix wording

### PR DESCRIPTION
**Pull request by marcoow**
as suggested by @daliwali

### CODE REVIEW

**Review by ganeshbsub — COMMENTED** [review]
<p>Also, as it has become a tradition already, <strong>simplabs will *invite* all workshop attendees to a shared dinner</strong> on the night of the first day 🍔🍹.</p>

"first workshop day" - I think the word workshop is unnecessary here.

**Comment by marcoow** [comment]
@ganeshbsub_ I don't know - I think _"first day"_ sounds strange actually, a bit like _"the first day of all days"_… Also _"shared"_ is unnecessary. Can you remove that and merge?

**Comment by ganeshbsub** [comment]
What about "invite all workshop attendees to dinner on the first day of the workshop"? Since we have dinner at night anyway.

**Comment by marcoow** [comment]
Yep, sounds good. I think it should be _"…workshop attendees for diner on the…"_

**Pull request merged**
